language: php

# required for "git tag" presence for MonorepoBuilder split and ChangelogLinker git tags resolver
# see https://github.com/travis-ci/travis-ci/issues/7422
git:
  depth: false

jobs:
  include:
    - stage: standards
      name: Checking standards
      php: 8.0
      script:
        - composer install
        - php vendor/bin/phpcs --standard=PSR1 ./packages --ignore=*/spec/*
        - php vendor/bin/phpcs --standard=PSR2 ./packages --ignore=*/spec/*
        - php vendor/bin/phpstan analyse ./packages --level max
    - &test-stage
      stage: test
      name: PHP 7.1
      php: 8.0
      script:
        - composer install
        - php vendor/bin/phpspec run
        - cd $TRAVIS_BUILD_DIR/packages/Aggrego/Domain
        - php $TRAVIS_BUILD_DIR/vendor/bin/behat
    - stage: split
      name: Split for repositories
      php: 8.0
      script: |
        if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then
          composer install
          vendor/bin/monorepo-builder split -v
        fi

stages:
  - standards
  - test
  - name: split
    if: branch = master
