version: '2'
services:
  php:
    image: php:7.1.19-cli-alpine
    volumes:
      - ./:/app
    working_dir: /app

  composer:
    image: composer:latest
    container_name: composer
    volumes_from:
      - php
    working_dir: /app